#! /usr/bin/perl
use File::Basename;
my $TEMPLATE='$HOME/.quickblog/template2.html';
my $EXTENSION='md';

opendir(D, ".") || die "Can't open directory: $!\n";
while (my $f = readdir(D)) {
	#~ my ($ext) = $f =~ /(\.[^.]+)$/;
	($file,$dir,$ext) = fileparse($f, qr/\.[^.]*/);
	if ($ext eq ".$EXTENSION") {
		my $cmd = "pandoc -s -o " . $file . ".html --template=$TEMPLATE --mathjax=https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML " . $file . ".$EXTENSION";
		system($cmd)
	}
}
closedir(D);
