#! /bin/bash
NAME=$1
EDITOR=geany
EXTENSION=md
if [ -f $NAME.md ]; then
	$EDITOR index.$EXTENSION
  $EDITOR "$NAME.$EXTENSION"
else
  echo "File $NAME.md doesn't exist so I'm not going to do anything"
fi
